version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - DB_HOST=database
      - REDIS_HOST=redis